# ==========================
# Spring Boot Configuration
# ==========================

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true



  data:
  #For debugging on dev machine.
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:8001}
      password: ""

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=contAInBallenbak;encrypt=false;trustServerCertificate=true
    username: contAIn
    password: contAIn
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


#For container 
#    redis:
#      host: ${SPRING_REDIS_HOST:Redis-service}
#      port: ${SPRING_REDIS_PORT:6379}
#      password: ""



#datasource:
#    url: jdbc:sqlserver://sql-express:1433;databaseName=contAInBallenbak;encrypt=false;trustServerCertificate=true
#    username: contAIn
#    password: contAIn123!
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

# ==========================
# Custom Application Properties
# ==========================

app:
  keystore:
    path: /app/config/Containselfsigned_cert.p12
