# ==========================
# Spring Boot Configuration
# ==========================

#debug: true

spring:
  # ---------- Flyway ----------
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-on-validation-error: true

  # ---------- Redis ----------
  data:
    redis:
      host: ${SPRING_REDIS_HOST:Redis-service}
      port: ${SPRING_REDIS_PORT:8001}
      password: ""

  # ---------- DataSource ----------
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=contAInBallenbak;encrypt=false;trustServerCertificate=true
    username: sa
    password: contAIn123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # ---------- JPA ----------
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  # ---------- ActiveMQ ----------
activemq:
  brokerUrl: tcp://localhost:61616
  user: admin
  password: admin

# ==========================
# Logging
# ==========================

logging:
  level:
    org.flywaydb.core: DEBUG

# ==========================
# Custom Application Properties
# ==========================

app:
  keystore:
    path: /app/config/Containselfsigned_cert.p12

alfresco:
  username: admin
  password: admin
  baseUrl: http://localhost:8080

ils:
  #username: admin
  #password: admin
  base-url: http://localhost:5000
