version: "3.9"

networks:
  ils-network:
    driver: bridge

services:
  redis:
    image: redis/redis-stack:latest
    container_name: Redis-service
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - ils-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-express
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "contAIn123!"
    ports:
      - "14330:1433"
    networks:
      - ils-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P contAIn123! -Q 'SELECT 1'"]
      interval: 10s
      retries: 10
      timeout: 5s

  contain-ils:
    image: ils-app
    container_name: Contain-ILS
    depends_on:
      redis:
        condition: service_healthy
      sqlserver:
        condition: service_healthy
    networks:
      - ils-network
    ports:
      - "5000:5000"
    volumes:
      - "C:/ContainOpenSource/Java/OpenSourceJava/ECM/src/main/resources/application.yml:/app/config/application.yml"
      - "C:/ContainOpenSource/Java/OpenSourceJava/ECM/src/main/resources/Containselfsigned_cert.p12:/app/config/Containselfsigned_cert.p12"
    environment:
      SPRING_CONFIG_LOCATION: "/app/config/application.yml"
      SPRING_REDIS_HOST: "Redis-service"
      SPRING_REDIS_PORT: "6379"
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://sqlserver:1433;databaseName=contAInBallenbak;encrypt=false"
      SPRING_DATASOURCE_USERNAME: "contAIn"
      SPRING_DATASOURCE_PASSWORD: "contAIn123!"
