name: ilstools
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    networks:
      - ils_ils_default
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ilstools
    volumes:
      - mongo_storage:/data/db

networks:
  ils_ils_default:
    external: true

volumes:
  mongo_storage: