spring:
  profiles:
    active: sp
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/contAInBallenbak
    username: contain
    password: contain
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 20000
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
# ---------------- ActiveMQ ----------------
activemq:
  brokerUrl: tcp://localhost:61616
  user: admin
  password: admin
  sharepoint-queue: sharepoint.delta.queue
  alfresco-queue: Consumer.MyJavaConsumer.VirtualTopic.alfresco.repo.events.nodes

# ---------------- Custom App ----------------
app:
  keystore:
    path: C:\ContainOpenSource\Java\OpenSourceJava\ils\src\main\resources\Containselfsigned_cert.p12

alfresco:
  username: admin
  password: admin
  baseUrl: http://localhost:8080

ils:
  base-url: http://localhost:5000
  uudiutilendpoint: http://localhost:5002/api/GetUUID
  bindendpoint: http://localhost:5000/api/Bind
  relocateendpoint: http://localhost:5000/api/RelocateIO
  DeltaLinkFile: "C:\\Temp\\storeddeltalinks.csv"