
# ==========================
# Spring Boot Configuration
# ==========================

name: ils

#debug: true

spring:

  redis:
    host: Redis-service
    port: 6379
  
  # ---------- Mongo DataSource ----------
  data:
    mongodb:
      uri: mongodb://admin:admin@mongo_db:27017/ilstools?authSource=admin

  
  datasource:
 #------------PostGress datasource -------------
    url: jdbc:postgresql://postgres-db:5432/contAInBallenbak
    username: contain
    password: contain
    driver-class-name: org.postgresql.Driver
    idle-timeout: 30000          # 30 seconds
    max-lifetime: 1800000        # 30 minutes
    connection-timeout: 30000    # 30 seconds
    leak-detection-threshold: 20000  # 20 seconds\
  jpa:
    hibernate:
      ddl-auto: update   # or create / create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
# ==========================
# Custom Application Properties
# ==========================

activemq:
  #brokerUrl: tcp://end-user-activemq-1:61616 Alfresco queue
alfresco:
  username: admin
  password: admin
  baseUrl: http://end-user-alfresco-1:8080
  sharepoint-queue: sharepoint.delta.queue
  alfresco-queue: Consumer.MyJavaConsumer.VirtualTopic.alfresco.repo.events.nodes

ils:
  uudiutilendpoint: http://ils-uuidutil-1:5002/api/GetUUID
  baseurl: http://receiver:8080
  bindendpoint: http://receiver:8080/api/Bind
  processspitemsendpoint: http://receiver:8080/api/ProcessChangedSharepointItem
  processalfresconodepoint: http://receiver:8080/api/ProcessChangedAlfrescoNode
  logiodeletedfromplatformendpoint: http://receiver:8080/api/logiodeletedfromplatform
  ruleenginemoveendpoint: http://receiver:8080/api/rules
  relocateendpoint: http://receiver:8080/api/MigrateIO
  ruleenginecontainerendpoint: http://kie-server:8080/kie-server/services/rest/server
  ruleengineendpoint: http://kie-server:8080/kie-server/services/rest/server/containers/{CONTAINER_ID}/dmn
  ruleengineprojectname: contAlnMigrationRuleset
  deltalinkfile: "/app/data/storeddeltalinks.csv"