name: ils

services:
  redis:
    image: redis/redis-stack:latest
    container_name: Redis-service
    ports:
    - "6379:6379"
    - "8001:8001"
    networks:
    - ils_ils_default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
      

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: contain
      POSTGRES_PASSWORD: contain
      POSTGRES_DB: contAInBallenbak  # <-- the database Spring Boot will use
    ports:
      - "5433:5432"
    networks:
    - ils_ils_default
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:


networks:
  ils_ils_default:
    external: true
