version: '3.8'

name : ils
services:
  uuidutil:
    build:
      context: C:/ContainOpenSource/Java/OpenSourceJava/ils
      dockerfile: uuidutil/Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ~/.m2/repository:/root/.m2/repository