
name: ils
services:

  # ==========================
  # Infrastructure
  # ==========================


#  postgres-db:
#    image: postgres:16
#    container_name: postgres-db
#    environment:
#      POSTGRES_DB: contAInBallenbak
#      POSTGRES_USER: contain
#      POSTGRES_PASSWORD: contain
#    ports:
#      - "5433:5432"
#    volumes:
#     - pgdata:/var/lib/postgresql/data
#    networks:
#      - ils-network

#  redis:
#    image: redis:7
#    container_name: Redis-service
#    ports:
#      - "6379:6379"
#    networks:
#      - ils-network


  # ==========================
  # Applications
  # ==========================

  receiver:
    build:
      context: .
      dockerfile: receiver/Dockerfile
    container_name: ils-receiver
    environment:
      SPRING_PROFILES_ACTIVE: receiver
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/contAInBallenbak
      SPRING_DATASOURCE_USERNAME: contain
      SPRING_DATASOURCE_PASSWORD: contain
      SPRING_REDIS_HOST: Redis-service
      SPRING_REDIS_PORT: 6379
      ACTIVEMQ_BROKERURL: tcp://activemq:61616
#    depends_on:
#      - postgres-db
#      - activemq
#      - redis
    networks:
      - ils-network


  sharepointpoller:
    build:
      context: .
      dockerfile: sharepointqueuepoller/Dockerfile
    container_name: ils-sharepointpoller
    environment:
      SPRING_PROFILES_ACTIVE: sp
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/contAInBallenbak
      SPRING_DATASOURCE_USERNAME: contain
      SPRING_DATASOURCE_PASSWORD: contain
      ACTIVEMQ_BROKERURL: tcp://activemq:61616
#    depends_on:
#      - postgres-db
#      - activemq
    networks:
      - ils-network


  uuidutil:
    build:
      context: .
      dockerfile: uuidutil/Dockerfile
    container_name: ils-uuidutil
    ports:
      - "5002:5002"
    environment:
      SPRING_PROFILES_ACTIVE: default
    networks:
      - ils-network


# ==========================
# Network
# ==========================
networks:
  ils-network:
    name: ils-network

volumes:
  pgdata: