server:
  port: 56000

  redis:
    host: Redis-service
    port: 6379

  ils:
    uudiutilendpoint: http://ils-uuidutil-1:5002/api/GetUUID
    baseurl: http://receiver:8080
    bindendpoint: http://receiver:8080/api/Bind
    processspitemsendpoint: http://receiver:8080/api/ProcessChangedSharepointItem
    processalfresconodepoint: http://receiver:8080/api/ProcessChangedAlfrescoNode
    logiodeletedfromplatformendpoint: http://receiver:8080/api/logiodeletedfromplatform
    ruleenginemoveendpoint: http://receiver:8080/api/rules
    taxonomyserviceendpoint: https://taxonomy-service-ssl:53000/api
    relocateendpoint: http://receiver:8080/api/MigrateIO
    ruleenginecontainerendpoint: http://kie-server:8080/kie-server/services/rest/server
    ruleengineendpoint: http://kie-server:8080/kie-server/services/rest/server/containers/{CONTAINER_ID}/dmn
    ruleengineprojectname: contAlnMigrationRuleset
    deltalinkfile: "/app/data/storeddeltalinks.csv"