name: RHBAPKIE

services:
  kie-server:
    image: quay.io/kiegroup/kie-server-showcase:7.73.0.Final
    container_name: kie-server
    ports:
      - "8180:8080"
    volumes:
      # Use an absolute path on your host machine outside the project folder
      - C:\rhpam-data\kie-server-data:/opt/jboss/wildfly/standalone/data
      - C:\rhpam-data\maven-storage:/opt/jboss/.m2/repository
    environment:
      - KIE_ADMIN_USER=admin
      - KIE_ADMIN_PWD=admin
      - KIE_SERVER_ID=rhpam-poc-server
      - KIE_SERVER_CONTROLLER=http://business-central:8080/business-central/rest/controller
      - KIE_SERVER_LOCATION=http://kie-server:8080/kie-server/services/rest/server
      - KIE_MAVEN_REPO=http://business-central:8080/business-central/maven2
      - KIE_SCANNER_INTERVAL=5000
      - JAVA_OPTS=-Dkie.maven.offline.force=false -Dorg.kie.server.sync.deploy=true
    networks:
      - ils_ils_default

networks:
  ils_ils_default:
    external: true