
name : ils
services:
  sharepointqueuepoller:
    build:
      context: C:/ContainOpenSource/Java/OpenSourceJava/ils
      dockerfile: sharepointqueuepoller/Dockerfile
    container_name: sharepointqueuepoller
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/contAInBallenbak
      SPRING_DATASOURCE_USERNAME: contain
      SPRING_DATASOURCE_PASSWORD: contain
      SPRING_CONFIG_LOCATION: /app/data/application.yaml
    ports:
      - "3001:3001"
    networks:
      - ils_ils_default


networks:
  ils_ils_default:
    external: true


