
name: ils
services:
  taxonomycacher:
    build:
      extra_hosts:
        - "host.docker.internal:host-gateway"
      context: ..
      dockerfile: taxonomycacher/Dockerfile
    container_name: taxonomycacher
    ports:
      - "60000:60000"
    networks:
      - ils_ils_default
    environment:
      # Use host.docker.internal to route from the container to your host machine
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017/tbl_iolog

networks:
  ils_ils_default:
    external: true

